In [1]:
import numpy as np

In [4]:
x = np.array((1,2))
print(x)

[1 2]


In [3]:
x

array([1, 2])

In [5]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
import time

st = time.time()
l = list(range(1, 100001))
et = time.time() 

a = et - st 
print(a) 


0.003913164138793945


In [15]:
arr = np.array(100000)
print(arr)

100000


In [19]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr.shape

(2, 4)

In [25]:
arr.shape


(2, 4)

In [26]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
!pip install --upgrade pandas

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pandas/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pandas/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) - skipping
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))) - skipping


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [28]:
!pip list

Package                      Version
---------------------------- --------------
about-time                   4.2.1
absl-py                      2.1.0
aiohttp                      3.9.1
aiohttp-retry                2.8.3
aiosignal                    1.3.1
alive-progress               3.2.0
anyio                        4.4.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.1.0
Babel                        2.15.0
beautifulsoup4               4.12.3
bleach                       6.1.0
catboost                     1.2.7
certifi                      2023.11.17
cffi                         1.16.0
charset-normalizer           3.3.2
click                        8.1.7
colorama                     0.4.6
comm                         0.2.2
comtypes                     1.2.0
contourpy                    1.2.

DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [29]:
dic = {"Name":["Niraj", "Dharmendra", "Gotham"], "Age":[34,35,36]}
dic

{'Name': ['Niraj', 'Dharmendra', 'Gotham'], 'Age': [34, 35, 36]}

In [33]:
import pandas as pd
df = pd.DataFrame(dic)

In [34]:
df.head()

Name  Age
0       Niraj   34
1  Dharmendra   35
2      Gotham   36

In [38]:
dic1 = {"Name":["Niraj", "Dharmendra", "Gotham"], "Age":[34,35,36], "Salary":[100, 200, 150], "Sex":["M", "M", "M"]}
dic1

{'Name': ['Niraj', 'Dharmendra', 'Gotham'],
 'Age': [34, 35, 36],
 'Salary': [100, 200, 150],
 'Sex': ['M', 'M', 'M']}

In [41]:
df = pd.DataFrame(dic1)

In [42]:
df.head()

Name  Age  Salary Sex
0       Niraj   34     100   M
1  Dharmendra   35     200   M
2      Gotham   36     150   M

In [45]:
df['Name'] [1]

'Dharmendra'

In [47]:
df.to_csv('test_df.csv')